version: '3.1'

services:
  client:
    container_name: screencloud-client
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - screencloud-networks

  # nginx:
  #   container_name: screencloud-nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '80:80'
  #   networks:
  #     - screencloud-networks

networks:
  screencloud-networks:
    driver: bridge
